import type { Metadata } from "next";
import "./styles/global.scss";
import { NoSsr } from "./components/NoSsr.jsx";

export const metadata: Metadata = {
  title: "nextMovie",
  description: "Pet project by Natalka Moroz. Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NoSsr>
      <html lang="en">
        <body>{children}</body>
      </html>
    </NoSsr>
  );
}
