import type { Metadata } from "next";
import "./styles/global.scss";

export const metadata: Metadata = {
  title: "nextMovie",
  description: "Pet project by Natalka Moroz. Generated by create-next-app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
